USE `eyoubika`;
/*Table structure for table `ta_FetchBreedBasic` */
DROP TABLE IF EXISTS `ta_FetchBreedBasic`;
CREATE TABLE `ta_FetchBreedBasic` (
	 `FBB_BreedId` int(10) NOT NULL ,
	 `FBB_BreedNo` varchar(64) default NULL ,
	 `FBB_Name` varchar(64) default NULL ,
	 `FBB_ShortName` varchar(64) default NULL ,
	 `FBB_IssueTime` varchar(64) default NULL ,
	 `FBB_IssueVolumn` varchar(64) default NULL ,
	 `FBB_IssuePrice` varchar(64) default NULL ,
	 `FBB_IssueStyle` varchar(64) default NULL ,
	 `FBB_IssueUnit` varchar(64) default NULL ,
	 `FBB_IssuePlace` varchar(64) default NULL ,
	 `FBB_InitUnit` varchar(64) default NULL ,
	 `FBB_Price` varchar(64) default NULL ,
	 `FBB_Picture` varchar(64) default NULL ,
	 `FBB_SerialNumber` varchar(64) default NULL ,
	 `FBB_FaceValue` varchar(64) default NULL ,
	 `FBB_FullSetNumber` varchar(64) default NULL ,
	 `FBB_FullSetPrice` varchar(64) default NULL ,
	 `FBB_FullSetFaceValue` varchar(64) default NULL ,
	 `FBB_FullSetMember` varchar(256) default NULL ,
	 `FBB_Specification` varchar(128) default NULL ,
	 `FBB_Quality` varchar(64) default NULL ,
	 `FBB_Finess` varchar(64) default NULL ,
	 `FBB_Category` varchar(64) default NULL ,
	 `FBB_Weight` varchar(64) default NULL ,
	 `FBB_FrontPic` varchar(128) default NULL ,
	 `FBB_BackPic` varchar(128) default NULL ,
	 `FBB_Manufacturer` varchar(64) default NULL ,
	 `FBB_Printing` varchar(64) default NULL ,
	 `FBB_Designer` varchar(64) default NULL ,
	 `FBB_AntiCounterfeiting` varchar(64) default NULL ,
	 `FBB_PerforationDegree` varchar(64) default NULL ,
	 `FBB_WholeNumber` varchar(64) default NULL ,
	 `FBB_WholeSpecif` varchar(64) default NULL ,
	 `FBB_PostImg` varchar(64) default NULL ,
	 `FBB_PostImgSepcif` varchar(64) default NULL ,
	 `FBB_Gum` varchar(64) default NULL ,
	 `FBB_FrontCover` varchar(64) default NULL ,
	 `FBB_BackCover` varchar(64) default NULL ,
	 `FBB_Photographer` varchar(64) default NULL ,
	 `FBB_Texture` varchar(64) default NULL ,
	 `FBB_System` varchar(64) default NULL ,
	 `FBB_Theme` varchar(64) default NULL ,
	 `FBB_Editor` varchar(64) default NULL ,
	 `FBB_BreedType` varchar(2) default NULL ,
	 `FBB_From` varchar(64) default NULL ,
	 `FBB_Unit` varchar(16) default NULL ,
	 `FBB_Status` varchar(2) default NULL ,
	PRIMARY KEY  (`FBB_BreedId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*Data for the table `ta_FetchBreedBasic` */

